disabled_rules:
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - SKUtilsUITests
  - Pods/AERecord
  - Pods/AlamofireImage
  - Pods/Alamofire
  - Pods/ObjectMapper
  - Pods/NVActivityIndicatorView
  - Pods/SwiftyDrop
file_length:
  warning: 300
  error: 350
variable_name:
  min_length: 2
line_length:
  warning: 150
  error: 160
